# playbook to configure the baseline amazon server

- name: Baseline Amazon Linux
  vars:
    varname1: "example"
  
  hosts: all
  gather_facts: no

  tasks:

   - name: Update yum
     yum: 
       name: '*'
       state: latest
     become: true

   - cron:
       name: "yum security"
       minute: "0"
       hour: "9"
       weekday: "*"
       job: "yum update --security -y"
     become: true
    
   - name: Install base tools
     yum: 
       name:
        - curl
        - python
        - unzip
        - python-pip
        - nc
        - mtr
       state: latest
     become: true

   - name: Install base tools (Python)
     pip:
       name: 
         - awscli
         - boto3
     become: true
