---
#
# Shared config for Packer
#

packer_defaults:
  instance_type: t3.micro
  use_spot_instances: false
  region: us-east-1
  encrypt_ami: false

packer_envs:
  prod:
    vpc: vpc-1234
    subnet: subnet-1234
    sg: sg-1234
    instance_profile: packer
  non-prod:
    vpc: vpc-4321
    subnet: subnet-4321
    sg: sg-4321
    instance_profile: packer

packer_baseimages:
  amz1:
    name: amzn1-ami-hvm-*-x86_64-gp2
    owner: amazon
  amz2:
    name: amzn2-ami-hvm-*-x86_64-gp2
    owner: amazon
  my_debian:
    name: name_of_my_debian_ami
    owner: 111111111111
